register_user:
    path: /users
    controller: App\Api\Action\User\UserAction::register
    methods: POST
get_all_users:
    path: /users
    controller: App\Api\Action\User\UserAction::getAll
    methods: GET